export const experiences = [
  {
    id: 1,
    company: "Hcode Technologies",
    role: "Software Developer",
    period: "Dec 2023 - Present",
    startDate: "Dec 2023",
    endDate: "Present",
    logo: "/company/hcode.png",
    description: [
      "Maintained web applications serving 200,000+ users with 45% stability improvement",
      "Optimized performance reducing load time by 60% through code splitting and lazy loading",
      "Improved Lighthouse scores from 65 to 95, increasing organic traffic by 35%",
      "Increased user engagement by 40% and reduced bug reports by 55%",
    ],
    side: "right",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 2,
    company: "Pixy Square",
    role: "Fullstack Developer",
    period: "May 2023 - Nov 2023",
    startDate: "May 2023",
    endDate: "Nov 2023",
    logo: "/company/pixy.webp",
    description: [
      "Developed 8+ full-stack applications with 85% client retention rate",
      "Achieved 90+ Lighthouse scores improving page load speeds by 50%",
      "Increased mobile engagement by 65% with responsive designs",
    ],
    side: "left",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    company: "Duckcart",
    role: "NodeJs Developer",
    period: "Nov 2022 - May 2023",
    startDate: "Nov 2022",
    endDate: "May 2023",
    logo: "/company/duckcart.png",
    description: [
      "Built backend handling 50,000+ daily API requests with 99.9% uptime",
      "Reduced response times by 70% and improved throughput by 3x using Redis",
      "Created 25+ RESTful endpoints reducing data errors by 80%",
    ],
    side: "right",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: 4,
    company: "Qwings",
    role: "Frontend Developer Intern",
    period: "Mar 2022 - Jul 2022",
    startDate: "Mar 2022",
    endDate: "Jul 2022",
    logo: "/company/qwings.png",
    description: [
      "Learned React.js and built 5+ responsive components",
      "Improved user satisfaction scores by 25% with UI features",
      "Participated in agile workflows and code reviews",
    ],
    side: "left",
    color: "from-orange-500 to-red-500",
  },
  {
    id: 5,
    company: "Avada",
    role: "Web Developer Intern",
    period: "Mar 2021 - Aug 2021",
    startDate: "Mar 2021",
    endDate: "Aug 2021",
    logo: "/company/avada.png",
    description: [
      "Learned HTML5, CSS3, and JavaScript fundamentals",
      "Contributed to 3+ projects improving mobile compatibility",
      "Optimized website assets reducing image sizes by 40%",
    ],
    side: "right",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: 6,
    company: "Skill Vertex",
    role: "MERN Stack Developer Intern",
    period: "Oct 2020 - Dec 2020",
    startDate: "Oct 2020",
    endDate: "Dec 2020",
    logo: "/company/skillvertex.png",
    description: [
      "Learned MERN stack fundamentals through guided projects",
      "Built 2 capstone projects (E-commerce and food delivery apps)",
      "Gained experience with RESTful APIs and authentication flows",
    ],
    side: "left",
    color: "from-yellow-500 to-orange-500",
  },
] as const;
